// packages/unplugin-gueleton/src/client/react/gueleton.tsx
import type { CSSProperties } from 'react'
import type { ComponentProps } from '../core'
import type { Primitive } from './primitive'
import { isNil, isUndefined, merge } from 'lodash-es'
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Provider, prune, skeleton } from '../core'
import { Slot } from './primitive/slot'
import { useMounted } from './utils'

type GueletonProps<DATA> = ComponentProps<DATA, CSSProperties> & React.ComponentPropsWithoutRef<typeof Primitive.div> & {
  children?: (params: { data: DATA | null | undefined }) => React.ReactNode
}

// eslint-disable-next-line ts/explicit-function-return-type
export function Gueleton<T>(props: GueletonProps<T>) {
  const {
    data,
    dataKey,
    loading = false,
    forceRender = false,
    prestoreData: prestoreDataProp,
    children,
    asChild,
    ...restProps
  } = props

  const containerRef = useRef<HTMLElement>(null)
  const [prestoreData, setPrestoreData] = useState<T | null | undefined>(undefined)
  const [prestoreDataResolved, setPrestoreDataResolved] = useState(false)
  const isMounted = useMounted()

  const options = useMemo(() => merge({}, Provider.options, props), [props])

  useEffect(() => {
    const loadPrestoreData = async (): Promise<void> => {
      if (isUndefined(prestoreDataProp)) {
        const data = await Provider.getPrestoreData<T>(dataKey)
        setPrestoreData(data)
        setPrestoreDataResolved(true)
      }
      else {
        setPrestoreData(prestoreDataProp)
      }
    }

    loadPrestoreData()
  }, [dataKey, prestoreDataProp])

  useEffect(() => {
    if (!prestoreDataResolved || !isUndefined(prestoreData) || isUndefined(data) || loading) {
      return
    }

    const savePrestoreData = async (): Promise<void> => {
      await Provider.setPrestoreData(dataKey, prune(data, options.limit))
      setPrestoreData(await Provider.getPrestoreData<T>(dataKey))
    }

    savePrestoreData()
  }, [prestoreDataResolved, loading, dataKey, data, prestoreData, options.limit])

  useEffect(() => {
    if (isNil(containerRef.current) || !isMounted || !loading) {
      return
    }

    const unmount = skeleton(containerRef.current, { ...options })
    return () => unmount()
  }, [isMounted, loading, options, prestoreData])

  const renderContent = useCallback(() => {
    if (loading) {
      if (!isUndefined(prestoreData) || forceRender) {
        return children?.({ data: prestoreData })
      }
      return null
    }
    else {
      return children?.({ data })
    }
  }, [loading, prestoreData, forceRender, children, data])

  return (
    <Slot
      ref={containerRef}
      {...restProps}
    >
      {renderContent()}
    </Slot>
  )
}

export default Gueleton

// packages/unplugin-gueleton/src/client/vue/gueleton.vue
<script lang="ts" setup generic="T">
import type { ComponentPublicInstance, CSSProperties } from 'vue'
import type { ComponentProps } from '../core'
import type { PrimitiveProps } from './primitive'
import { isNil, isUndefined, merge } from 'lodash-es'
import { computed, ref, watch } from 'vue'
import { Provider, prune, skeleton } from '../core'
import { Primitive } from './primitive'
import { useMounted } from './utils'

type GueletonProps<DATA> = ComponentProps<DATA, CSSProperties> & PrimitiveProps

const props = defineProps<GueletonProps<T>>()

defineSlots<{
  default: (params: { data: T | null | undefined }) => any
}>()

const options = computed(() => merge({}, Provider.options, props))
const data = computed(() => props.data)
const dataKey = computed(() => props.dataKey)
const loading = computed(() => props.loading ?? false)
const forceRender = computed(() => props.forceRender ?? false)

const prestoreData = ref<any | null | undefined>(undefined)
const prestoreDataResolved = ref(false)
watch([dataKey, () => props.prestoreData], async ([_dataKey, _prestoreData]) => {
  if (isUndefined(_prestoreData)) {
    prestoreData.value = await Provider.getPrestoreData(_dataKey)
    prestoreDataResolved.value = true
  }
  else {
    prestoreData.value = _prestoreData
  }
}, { immediate: true })

watch([prestoreDataResolved, loading, dataKey, data] as const, async ([_resolved, _loading, _dataKey, _data]) => {
  if (!_resolved || !isUndefined(prestoreData.value) || isUndefined(_data) || _loading) {
    return
  }
  await Provider.setPrestoreData(_dataKey, prune(_data, options.value.limit))
  prestoreData.value = await Provider.getPrestoreData(_dataKey)
})

const containerRef = ref<Element | ComponentPublicInstance | null>(null)
watch(
  [containerRef, useMounted(), loading, options, prestoreData],
  async ([_container, _isMounted, _loading, _options, _prestoreData], _, onCleanup) => {
    if (isNil(_container) || !_isMounted || !_loading) {
      return
    }
    const _el = _container instanceof Element ? _container : _container.$el
    if (isNil(_el)) {
      return
    }
    const unmount = skeleton(_el, { ..._options })
    onCleanup(() => unmount())
  },
  { immediate: true, flush: 'post' },
)
</script>

<template>
  <Primitive
    ref="containerRef"
    :as="as"
    :as-child="asChild"
  >
    <template v-if="loading">
      <slot v-if="!isUndefined(prestoreData) || forceRender" :data="prestoreData" />
    </template>
    <template v-else>
      <slot :data="data" />
    </template>
  </Primitive>
</template>
